algoritmo "ESTRUTURA CONDICIONAL COMPOSTA"

// Descobrir se o número é par ou ímpar utilizando Estrutura Condicional Composta

var
   N: Inteiro
inicio
      Escreva ("Digite um número qualquer: ")
      Leia (N)
      
      Se (N % 2 = 0) entao
         EscrevaL ("O número", N, " é PAR!")
      senao
         EscrevaL ("O número", N, " é IMPAR!")
      FimSe
      
      // % Significa o resto da divisão inteira
      
fimalgoritmo